use_frameworks!

platform :ios, '10.0'

target 'MyCocoapodsBitarLibrary_Example' do
  pod 'MyCocoapodsBitarLibrary', :path => '../'

  target 'MyCocoapodsBitarLibrary_Tests' do
    inherit! :search_paths

    
  end
end
